# Generated by Django 3.1.7 on 2021-04-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technoweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCorner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_mobile', models.CharField(max_length=100)),
                ('student_dob', models.DateField()),
                ('student_address', models.CharField(max_length=300)),
                ('student_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('student_qualification', models.CharField(max_length=300)),
                ('student_college', models.CharField(max_length=300)),
                ('student_academic_marks', models.CharField(max_length=300)),
                ('student_selected_language', models.CharField(max_length=200)),
                ('student_fee_plan', models.CharField(choices=[('Lumpsum', 'Lumpsum'), ('Installments', 'Installments')], max_length=100)),
            ],
        ),
    ]
