# Generated by Django 3.1.7 on 2021-04-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technoweb', '0002_studentcorner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcorner',
            name='student_selected_language',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Android', 'Android'), ('Digital Marketing', 'Digital Marketing'), ('Personality Development', 'Personality Development'), ('Spoken English', 'Spoken English')], max_length=200),
        ),
    ]
