# Generated by Django 3.1.7 on 2021-04-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technoweb', '0003_auto_20210405_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrCorner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=300)),
                ('contact_person', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=200)),
                ('company_registered_address', models.CharField(max_length=300)),
                ('total_requirements', models.IntegerField(max_length=20)),
                ('qualification_required', models.CharField(max_length=300)),
                ('job_experience', models.CharField(max_length=100)),
                ('communication_skill', models.CharField(max_length=100)),
                ('annual_salary', models.CharField(max_length=200)),
                ('cab_facility', models.CharField(max_length=100)),
                ('incentive_plans', models.CharField(max_length=200)),
                ('interview_process', models.CharField(max_length=100)),
                ('group_discussion', models.CharField(max_length=100)),
                ('hr_round', models.CharField(max_length=10)),
                ('technical_round', models.CharField(max_length=10)),
                ('work_environment', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('hiring_position', models.CharField(max_length=100)),
                ('major_responsibities', models.CharField(max_length=500)),
            ],
        ),
    ]
