# Generated by Django 3.1.7 on 2021-04-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technoweb', '0004_hrcorner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrcorner',
            name='total_requirements',
            field=models.IntegerField(),
        ),
    ]
