# Generated by Django 2.2.7 on 2021-04-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technoweb', '0007_askquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('skype_id', models.CharField(max_length=100)),
                ('project_details', models.CharField(max_length=500)),
            ],
        ),
    ]
