# Generated by Django 2.2.7 on 2021-04-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technoweb', '0008_softwaredevelopment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaredevelopment',
            name='project_details',
            field=models.CharField(max_length=200),
        ),
    ]
