# Generated by Django 2.2.7 on 2021-04-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technoweb', '0010_auto_20210408_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaredevelopment',
            name='project_details',
            field=models.CharField(max_length=200),
        ),
    ]
