# Generated by Django 3.1.7 on 2021-04-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technoweb', '0011_auto_20210408_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwaredevelopment',
            old_name='mobile',
            new_name='contact',
        ),
    ]
