# Generated by Django 3.1.7 on 2021-04-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technoweb', '0012_auto_20210408_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcorner',
            name='student_upload_resume',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
