# Generated by Django 3.1.7 on 2021-04-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technoweb', '0013_studentcorner_student_upload_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcorner',
            name='student_current_organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentcorner',
            name='student_currently_working',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcorner',
            name='student_designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentcorner',
            name='student_total_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
